### ISSUE TITLE
Theme Customization guide

### ISSUE THREAD

**Issue by gpessa** [onfido/react-native-sdk#37]
I'm trying to personalize the colors but I feel like is not working or I'm doing something wrong.
Could you please explain better this step:

`you should add colors.json file to your xcode project as bundle resource. You can create symbolic link (rather than copy paste) to prevent redundancy`

And after I performed those steps, do I have to clean the project? Or rebuild it?

**Comment by gpessa** [comment]
Found a solution!

**Comment by eranda-blott** [comment]
any information ? for them customisations

**Comment by artan-monochain** [comment]
> Found a solution!

Very helpful, thanks

**Comment by gpessa** [comment]
> > Found a solution!
> 
> Very helpful, thanks

mmm now I don't remember exactly. I had to use XCODE to import the json in the project.

**Comment by DominicTobias** [comment]
Thanks but where do you import it once XCode is opened? In Resources or...? And how do you symlink it? I'm tempted to put it in src/assets since files there get automatically added to Resources

![Screenshot 2022-09-07 at 5 00 12 PM](https://user-images.githubusercontent.com/760314/188925208-3c8b303d-2e1e-40ff-9931-77b50bf2b2c8.png)
